
### Get request waiting a lognormal time
GET http://localhost:5000/wait/lognormal
Accept: application/json

### Get request that mirrors the headers
GET http://localhost:5000/mirror/headers
Accept: application/json

### Get request that returns given response code
GET http://localhost:5000/response/419
Accept: application/json

### POST request that save request in log
POST http://localhost:5000/log
Content-Type: application/json

{
  "temperature": 22.5,
  "humidity": 65
}
###


